"""
taxonomy/__init__.py  —  Full LeaseLoft vendor taxonomy
All 63 leaf-node categories with Yelp aliases, Google place types, keywords, and priorities.
"""

TAXONOMY_LEAF_NODES = [
    # PLUMBING
    {"code": "PLB.GEN", "parent": "PLB", "display_name": "General Plumbing",
     "yelp_aliases": ["plumbing", "localservices"], "google_place_types": ["plumber"],
     "keywords": ["plumber", "pipe", "faucet", "leak", "sewer", "water line", "drain", "toilet", "sink", "fixture"], "priority": 1},
    {"code": "PLB.EMR", "parent": "PLB", "display_name": "Emergency Plumbing",
     "yelp_aliases": ["plumbing"], "google_place_types": ["plumber"],
     "keywords": ["emergency plumber", "24 hour plumber", "burst pipe", "flooding", "water emergency"], "priority": 1},
    {"code": "PLB.DRN", "parent": "PLB", "display_name": "Drain Cleaning",
     "yelp_aliases": ["draincleaning", "plumbing"], "google_place_types": ["plumber"],
     "keywords": ["drain cleaning", "clogged drain", "rooter", "hydro jetting", "sewer cleaning"], "priority": 2},
    {"code": "PLB.WHR", "parent": "PLB", "display_name": "Water Heater Repair/Install",
     "yelp_aliases": ["waterheaterinstallrepair", "plumbing"], "google_place_types": ["plumber"],
     "keywords": ["water heater", "hot water", "tankless", "water heater repair", "boiler"], "priority": 2},
    {"code": "PLB.PIP", "parent": "PLB", "display_name": "Pipe Repair & Repiping",
     "yelp_aliases": ["plumbing"], "google_place_types": ["plumber"],
     "keywords": ["repiping", "pipe replacement", "copper pipe", "PVC pipe", "pipe repair", "gas line"], "priority": 2},
    # HVAC
    {"code": "HVC.ACR", "parent": "HVC", "display_name": "AC Repair",
     "yelp_aliases": ["aircondrepair", "hvac", "airconditioning"], "google_place_types": ["hvac_contractor"],
     "keywords": ["AC repair", "air conditioning", "AC service", "cooling system", "refrigerant", "compressor"], "priority": 1},
    {"code": "HVC.HEA", "parent": "HVC", "display_name": "Heating Repair",
     "yelp_aliases": ["heatingair", "hvac", "furnacerepair"], "google_place_types": ["hvac_contractor"],
     "keywords": ["heating repair", "furnace repair", "heat pump", "boiler repair", "gas heat", "heating system"], "priority": 1},
    {"code": "HVC.DCL", "parent": "HVC", "display_name": "Duct Cleaning",
     "yelp_aliases": ["hvac", "ductwork"], "google_place_types": ["hvac_contractor"],
     "keywords": ["duct cleaning", "air duct", "ductwork", "air quality", "ventilation cleaning"], "priority": 3},
    {"code": "HVC.MNS", "parent": "HVC", "display_name": "Mini-Split Install",
     "yelp_aliases": ["hvac"], "google_place_types": ["hvac_contractor"],
     "keywords": ["mini split", "ductless AC", "ductless system", "Mitsubishi", "Daikin", "LG inverter"], "priority": 3},
    {"code": "HVC.MNT", "parent": "HVC", "display_name": "HVAC Maintenance",
     "yelp_aliases": ["hvac"], "google_place_types": ["hvac_contractor"],
     "keywords": ["HVAC maintenance", "tune up", "annual service", "filter replacement", "AC checkup"], "priority": 2},
    # ELECTRICAL
    {"code": "ELC.GEN", "parent": "ELC", "display_name": "General Electrical",
     "yelp_aliases": ["electricians"], "google_place_types": ["electrician"],
     "keywords": ["electrician", "electrical repair", "wiring", "outlets", "switches", "circuit", "breaker"], "priority": 1},
    {"code": "ELC.PNL", "parent": "ELC", "display_name": "Panel Upgrade",
     "yelp_aliases": ["electricians"], "google_place_types": ["electrician"],
     "keywords": ["panel upgrade", "electrical panel", "service upgrade", "200 amp", "breaker box", "load center"], "priority": 2},
    {"code": "ELC.EVC", "parent": "ELC", "display_name": "EV Charger Installation",
     "yelp_aliases": ["electricians", "evchargingstations"], "google_place_types": ["electrician"],
     "keywords": ["EV charger", "electric vehicle charger", "Level 2 charger", "EVSE", "Tesla charger"], "priority": 3},
    {"code": "ELC.EMR", "parent": "ELC", "display_name": "Emergency Electrical",
     "yelp_aliases": ["electricians"], "google_place_types": ["electrician"],
     "keywords": ["emergency electrician", "power outage", "electrical emergency", "24 hour electrician"], "priority": 1},
    {"code": "ELC.LTG", "parent": "ELC", "display_name": "Lighting Installation",
     "yelp_aliases": ["electricians", "lightingfixtures"], "google_place_types": ["electrician"],
     "keywords": ["lighting installation", "recessed lights", "chandelier install", "outdoor lighting", "LED upgrade"], "priority": 3},
    # ROOFING
    {"code": "ROF.REP", "parent": "ROF", "display_name": "Roof Repair",
     "yelp_aliases": ["roofing"], "google_place_types": ["roofing_contractor"],
     "keywords": ["roof repair", "leak repair", "shingle repair", "roof patch", "flashing repair"], "priority": 1},
    {"code": "ROF.RPL", "parent": "ROF", "display_name": "Roof Replacement",
     "yelp_aliases": ["roofing"], "google_place_types": ["roofing_contractor"],
     "keywords": ["roof replacement", "new roof", "reroof", "asphalt shingles", "metal roof", "tile roof"], "priority": 2},
    {"code": "ROF.GUT", "parent": "ROF", "display_name": "Gutter Cleaning & Repair",
     "yelp_aliases": ["gutterservices", "roofing"], "google_place_types": ["roofing_contractor"],
     "keywords": ["gutter cleaning", "gutter repair", "downspout", "leaf guard", "gutter installation"], "priority": 2},
    {"code": "ROF.SKY", "parent": "ROF", "display_name": "Skylight Installation",
     "yelp_aliases": ["roofing"], "google_place_types": ["roofing_contractor"],
     "keywords": ["skylight", "Velux", "skylight installation", "skylight repair", "roof window"], "priority": 4},
    # LANDSCAPING
    {"code": "LND.LAW", "parent": "LND", "display_name": "Lawn Mowing & Maintenance",
     "yelp_aliases": ["landscaping", "lawnservices"], "google_place_types": ["landscaper"],
     "keywords": ["lawn mowing", "grass cutting", "lawn care", "weekly lawn", "lawn maintenance", "edging"], "priority": 2},
    {"code": "LND.TRE", "parent": "LND", "display_name": "Tree Service",
     "yelp_aliases": ["treeservices", "landscaping"], "google_place_types": ["landscaper"],
     "keywords": ["tree removal", "tree trimming", "stump grinding", "arborist", "tree cutting"], "priority": 2},
    {"code": "LND.IRR", "parent": "LND", "display_name": "Irrigation & Sprinkler",
     "yelp_aliases": ["irrigation", "landscaping"], "google_place_types": ["landscaper"],
     "keywords": ["sprinkler system", "irrigation repair", "lawn sprinkler", "drip irrigation"], "priority": 3},
    {"code": "LND.HRD", "parent": "LND", "display_name": "Hardscaping & Pavers",
     "yelp_aliases": ["landscaping", "paversservicesproducts"], "google_place_types": ["landscaper"],
     "keywords": ["hardscape", "paver installation", "patio", "walkway", "retaining wall", "outdoor pavers"], "priority": 4},
    {"code": "LND.SNW", "parent": "LND", "display_name": "Snow Removal",
     "yelp_aliases": ["snowremoval", "landscaping"], "google_place_types": ["landscaper"],
     "keywords": ["snow removal", "snow plowing", "ice removal", "de-icing", "snow blowing", "driveway snow"], "priority": 2},
    # CLEANING
    {"code": "CLN.MOV", "parent": "CLN", "display_name": "Move-Out Cleaning",
     "yelp_aliases": ["homecleaning", "movingcleaners"], "google_place_types": ["house_cleaning_service"],
     "keywords": ["move out cleaning", "move in cleaning", "deep clean", "end of tenancy", "turnover cleaning"], "priority": 1},
    {"code": "CLN.DEP", "parent": "CLN", "display_name": "Deep Cleaning",
     "yelp_aliases": ["homecleaning"], "google_place_types": ["house_cleaning_service"],
     "keywords": ["deep cleaning", "spring cleaning", "one-time cleaning", "thorough clean"], "priority": 2},
    {"code": "CLN.CAR", "parent": "CLN", "display_name": "Carpet Cleaning",
     "yelp_aliases": ["carpetcleaning"], "google_place_types": ["house_cleaning_service"],
     "keywords": ["carpet cleaning", "steam cleaning", "upholstery cleaning", "rug cleaning", "stain removal"], "priority": 2},
    {"code": "CLN.WIN", "parent": "CLN", "display_name": "Window Cleaning",
     "yelp_aliases": ["windowwashing"], "google_place_types": ["house_cleaning_service"],
     "keywords": ["window cleaning", "window washing", "exterior window", "glass cleaning"], "priority": 3},
    {"code": "CLN.PWS", "parent": "CLN", "display_name": "Pressure Washing",
     "yelp_aliases": ["pressurewashers", "homecleaning"], "google_place_types": ["house_cleaning_service"],
     "keywords": ["pressure washing", "power washing", "soft washing", "driveway cleaning", "deck cleaning"], "priority": 3},
    # PEST CONTROL
    {"code": "PST.GEN", "parent": "PST", "display_name": "General Pest Control",
     "yelp_aliases": ["pestcontrol"], "google_place_types": ["pest_control_service"],
     "keywords": ["pest control", "bug spray", "exterminator", "insect control", "ant", "cockroach"], "priority": 1},
    {"code": "PST.TRM", "parent": "PST", "display_name": "Termite Treatment",
     "yelp_aliases": ["pestcontrol"], "google_place_types": ["pest_control_service"],
     "keywords": ["termite control", "termite treatment", "termite inspection", "wood destroying insects"], "priority": 1},
    {"code": "PST.ROD", "parent": "PST", "display_name": "Rodent Control",
     "yelp_aliases": ["pestcontrol"], "google_place_types": ["pest_control_service"],
     "keywords": ["mouse removal", "rat control", "rodent exterminator", "rodent exclusion", "mouse trap"], "priority": 2},
    {"code": "PST.BED", "parent": "PST", "display_name": "Bed Bug Treatment",
     "yelp_aliases": ["pestcontrol"], "google_place_types": ["pest_control_service"],
     "keywords": ["bed bug treatment", "bed bug heat treatment", "bed bug exterminator", "bedbug"], "priority": 2},
    # GENERAL CONTRACTOR
    {"code": "GCT.REM", "parent": "GCT", "display_name": "Home Remodeling",
     "yelp_aliases": ["contractorsremodeling", "generalhome"], "google_place_types": ["general_contractor"],
     "keywords": ["remodeling", "renovation", "kitchen remodel", "bathroom remodel", "home renovation"], "priority": 2},
    {"code": "GCT.ADD", "parent": "GCT", "display_name": "Room Additions",
     "yelp_aliases": ["contractorsremodeling"], "google_place_types": ["general_contractor"],
     "keywords": ["room addition", "home addition", "garage conversion", "ADU", "sunroom"], "priority": 3},
    {"code": "GCT.DRY", "parent": "GCT", "display_name": "Drywall Repair & Install",
     "yelp_aliases": ["drywall", "generalhome"], "google_place_types": ["general_contractor"],
     "keywords": ["drywall repair", "drywall installation", "sheetrock", "drywall patch", "wall repair"], "priority": 2},
    {"code": "GCT.INS", "parent": "GCT", "display_name": "Insulation",
     "yelp_aliases": ["insulation"], "google_place_types": ["general_contractor"],
     "keywords": ["insulation installation", "attic insulation", "spray foam", "blown-in insulation"], "priority": 3},
    # PAINTING
    {"code": "PNT.INT", "parent": "PNT", "display_name": "Interior Painting",
     "yelp_aliases": ["painters"], "google_place_types": ["painter"],
     "keywords": ["interior painting", "house painter", "interior painter", "wall painting", "ceiling painting"], "priority": 1},
    {"code": "PNT.EXT", "parent": "PNT", "display_name": "Exterior Painting",
     "yelp_aliases": ["painters"], "google_place_types": ["painter"],
     "keywords": ["exterior painting", "house painting", "siding paint", "outdoor painting", "stucco painting"], "priority": 2},
    {"code": "PNT.CAB", "parent": "PNT", "display_name": "Cabinet Painting & Refinishing",
     "yelp_aliases": ["painters", "cabinetry"], "google_place_types": ["painter"],
     "keywords": ["cabinet painting", "cabinet refinishing", "cabinet refacing", "kitchen cabinet paint"], "priority": 3},
    # FLOORING
    {"code": "FLR.HRD", "parent": "FLR", "display_name": "Hardwood Floor Install/Refinish",
     "yelp_aliases": ["flooring", "hardwoodfloors"], "google_place_types": ["flooring_contractor"],
     "keywords": ["hardwood flooring", "wood floor installation", "hardwood refinishing", "floor sanding", "oak flooring"], "priority": 2},
    {"code": "FLR.CAR", "parent": "FLR", "display_name": "Carpet Installation",
     "yelp_aliases": ["carpetinstallation", "flooring"], "google_place_types": ["flooring_contractor"],
     "keywords": ["carpet installation", "carpet replacement", "new carpet", "carpet stretching"], "priority": 2},
    {"code": "FLR.TIL", "parent": "FLR", "display_name": "Tile Installation",
     "yelp_aliases": ["tilinginstallation", "flooring"], "google_place_types": ["flooring_contractor"],
     "keywords": ["tile installation", "ceramic tile", "porcelain tile", "backsplash", "bathroom tile"], "priority": 2},
    {"code": "FLR.LVP", "parent": "FLR", "display_name": "LVP / Laminate Install",
     "yelp_aliases": ["flooring"], "google_place_types": ["flooring_contractor"],
     "keywords": ["LVP", "luxury vinyl plank", "laminate flooring", "vinyl flooring", "waterproof flooring"], "priority": 2},
    # APPLIANCE REPAIR
    {"code": "APP.REF", "parent": "APP", "display_name": "Refrigerator Repair",
     "yelp_aliases": ["appliancerepair"], "google_place_types": ["appliance_repair_service"],
     "keywords": ["refrigerator repair", "fridge repair", "freezer repair", "ice maker repair"], "priority": 2},
    {"code": "APP.WDR", "parent": "APP", "display_name": "Washer/Dryer Repair",
     "yelp_aliases": ["appliancerepair"], "google_place_types": ["appliance_repair_service"],
     "keywords": ["washer repair", "dryer repair", "washing machine", "laundry appliance"], "priority": 2},
    {"code": "APP.DWS", "parent": "APP", "display_name": "Dishwasher Repair",
     "yelp_aliases": ["appliancerepair"], "google_place_types": ["appliance_repair_service"],
     "keywords": ["dishwasher repair", "dishwasher not draining", "dishwasher leaking", "Bosch dishwasher"], "priority": 3},
    {"code": "APP.OVN", "parent": "APP", "display_name": "Oven/Range/Stove Repair",
     "yelp_aliases": ["appliancerepair"], "google_place_types": ["appliance_repair_service"],
     "keywords": ["oven repair", "stove repair", "range repair", "gas stove", "electric oven", "burner repair"], "priority": 3},
    # LOCKSMITH
    {"code": "LCK.RKY", "parent": "LCK", "display_name": "Rekey Service",
     "yelp_aliases": ["locksmiths"], "google_place_types": ["locksmith"],
     "keywords": ["rekey", "rekeying", "change locks", "rekey service", "lock change"], "priority": 1},
    {"code": "LCK.INS", "parent": "LCK", "display_name": "Lock Installation",
     "yelp_aliases": ["locksmiths"], "google_place_types": ["locksmith"],
     "keywords": ["lock installation", "deadbolt install", "smart lock", "Schlage", "Kwikset"], "priority": 2},
    {"code": "LCK.EMR", "parent": "LCK", "display_name": "Emergency Lockout",
     "yelp_aliases": ["locksmiths"], "google_place_types": ["locksmith"],
     "keywords": ["emergency locksmith", "lockout service", "house lockout", "24 hour locksmith", "locked out"], "priority": 1},
    # POOL & SPA
    {"code": "POL.WKL", "parent": "POL", "display_name": "Weekly Pool Service",
     "yelp_aliases": ["poolsandhotspas", "swimmingpools"], "google_place_types": ["swimming_pool"],
     "keywords": ["pool service", "pool cleaning", "pool maintenance", "weekly pool", "pool chemical"], "priority": 2},
    {"code": "POL.REP", "parent": "POL", "display_name": "Pool Repair & Equipment",
     "yelp_aliases": ["poolsandhotspas"], "google_place_types": ["swimming_pool"],
     "keywords": ["pool repair", "pool pump", "pool filter", "pool heater", "pool leak", "pool equipment"], "priority": 2},
    {"code": "POL.SPA", "parent": "POL", "display_name": "Spa / Hot Tub Service",
     "yelp_aliases": ["poolsandhotspas"], "google_place_types": ["swimming_pool"],
     "keywords": ["spa service", "hot tub service", "hot tub repair", "jacuzzi repair", "spa chemicals"], "priority": 3},
    # WINDOWS & DOORS
    {"code": "WND.REP", "parent": "WND", "display_name": "Window Replacement",
     "yelp_aliases": ["windowsinstallation"], "google_place_types": ["window_installation_service"],
     "keywords": ["window replacement", "new windows", "double pane", "energy efficient windows", "vinyl windows"], "priority": 2},
    {"code": "WND.DOR", "parent": "WND", "display_name": "Door Installation & Repair",
     "yelp_aliases": ["doorrepair", "windowsinstallation"], "google_place_types": ["window_installation_service"],
     "keywords": ["door installation", "door replacement", "exterior door", "interior door", "sliding door"], "priority": 2},
    {"code": "WND.GLS", "parent": "WND", "display_name": "Glass Repair & Replacement",
     "yelp_aliases": ["glassandmirrors"], "google_place_types": ["glass_shop"],
     "keywords": ["glass repair", "broken window", "glass replacement", "window glass", "mirror installation"], "priority": 3},
    # HANDYMAN
    {"code": "HND.GEN", "parent": "HND", "display_name": "General Handyman",
     "yelp_aliases": ["handyman", "generalhome"], "google_place_types": ["handyman"],
     "keywords": ["handyman", "home repair", "fix it", "odd jobs", "general repair", "home maintenance"], "priority": 1},
    {"code": "HND.FRN", "parent": "HND", "display_name": "Furniture Assembly",
     "yelp_aliases": ["handyman", "furnitureassembly"], "google_place_types": ["handyman"],
     "keywords": ["furniture assembly", "IKEA assembly", "flat pack", "bookshelf assembly", "bed frame assembly"], "priority": 3},
    {"code": "HND.TVW", "parent": "HND", "display_name": "TV Mounting",
     "yelp_aliases": ["handyman", "tvmounting"], "google_place_types": ["handyman"],
     "keywords": ["TV mounting", "TV wall mount", "television mounting", "flat screen mount", "bracket install"], "priority": 4},
    {"code": "HND.CLK", "parent": "HND", "display_name": "Caulking & Weatherstripping",
     "yelp_aliases": ["handyman"], "google_place_types": ["handyman"],
     "keywords": ["caulking", "weatherstripping", "draft proofing", "sealing", "bathroom caulk", "door seal"], "priority": 3},
    # JUNK / DUMPSTER
    {"code": "JNK.RMV", "parent": "JNK", "display_name": "Junk Removal & Hauling",
     "yelp_aliases": ["junkremovalandhauling", "trashcollection"], "google_place_types": ["moving_company"],
     "keywords": ["junk removal", "hauling", "debris removal", "trash removal", "furniture removal"], "priority": 2},
    {"code": "DMP.RNT", "parent": "DMP", "display_name": "Dumpster Rental",
     "yelp_aliases": ["truckrentallocations", "junkremovalandhauling"], "google_place_types": ["moving_company"],
     "keywords": ["dumpster rental", "roll-off dumpster", "container rental", "debris box", "dumpster delivery"], "priority": 3},
    # SPECIALTY
    {"code": "MLD.REM", "parent": "MLD", "display_name": "Mold Testing & Remediation",
     "yelp_aliases": ["environmental_abatement", "waterdamagerestoration"], "google_place_types": ["environmental_consultant"],
     "keywords": ["mold remediation", "mold removal", "mold testing", "mold inspection", "black mold"], "priority": 1},
    {"code": "WDM.RST", "parent": "WDM", "display_name": "Water Damage Restoration",
     "yelp_aliases": ["waterdamagerestoration"], "google_place_types": ["general_contractor"],
     "keywords": ["water damage", "flood damage", "water restoration", "water extraction", "drying", "dehumidification"], "priority": 1},
    {"code": "FND.REP", "parent": "FND", "display_name": "Foundation Repair & Waterproofing",
     "yelp_aliases": ["foundationrepair"], "google_place_types": ["general_contractor"],
     "keywords": ["foundation repair", "foundation crack", "basement waterproofing", "sump pump", "pier and beam"], "priority": 2},
]

# Quick lookup maps
YELP_ALIAS_TO_CATEGORY: dict[str, str] = {}
GOOGLE_TYPE_TO_CATEGORY: dict[str, str] = {}

for node in TAXONOMY_LEAF_NODES:
    for alias in node.get("yelp_aliases", []):
        if alias not in YELP_ALIAS_TO_CATEGORY:
            YELP_ALIAS_TO_CATEGORY[alias] = node["code"]
    for gtype in node.get("google_place_types", []):
        if gtype not in GOOGLE_TYPE_TO_CATEGORY:
            GOOGLE_TYPE_TO_CATEGORY[gtype] = node["code"]

CATEGORY_BY_CODE: dict[str, dict] = {node["code"]: node for node in TAXONOMY_LEAF_NODES}
